"""add Listing and GeocodeCache

Revision ID: 017cbba358ec
Revises: 8077e05f4c1f
Create Date: 2026-06-12 22:04:42.654051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017cbba358ec'
down_revision = '8077e05f4c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geocode_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_key', sa.String(length=500), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address_key')
    )
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_listing_id', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('listing_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price_cents', sa.BigInteger(), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('postal_code', sa.String(length=15), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('lot_sqft', sa.Integer(), nullable=True),
    sa.Column('building_sqft', sa.Integer(), nullable=True),
    sa.Column('acres', sa.Float(), nullable=True),
    sa.Column('beds', sa.Float(), nullable=True),
    sa.Column('baths_total', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('zoning_code', sa.String(length=40), nullable=True),
    sa.Column('far_max', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_listing_id', name='uq_listing_source_pair')
    )
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.create_index('ix_listing_state_county', ['state', 'county'], unique=False)
        batch_op.create_index('ix_listing_state_price', ['state', 'price_cents'], unique=False)
        batch_op.create_index('ix_listing_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index('ix_listing_status')
        batch_op.drop_index('ix_listing_state_price')
        batch_op.drop_index('ix_listing_state_county')

    op.drop_table('listing')
    op.drop_table('geocode_cache')
    # ### end Alembic commands ###
