"""add nyc_pluto_lot and bbl_cache

Revision ID: e21ad3a51d8b
Revises: 017cbba358ec
Create Date: 2026-07-07 23:14:52.739185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21ad3a51d8b'
down_revision = '017cbba358ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbl_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_key', sa.String(length=500), nullable=False),
    sa.Column('bbl', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address_key')
    )
    op.create_table('nyc_pluto_lot',
    sa.Column('bbl', sa.String(length=10), nullable=False),
    sa.Column('borough', sa.String(length=2), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('lot', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('zipcode', sa.String(length=10), nullable=True),
    sa.Column('lot_area', sa.Integer(), nullable=True),
    sa.Column('bldg_area', sa.Integer(), nullable=True),
    sa.Column('com_area', sa.Integer(), nullable=True),
    sa.Column('res_area', sa.Integer(), nullable=True),
    sa.Column('num_floors', sa.Float(), nullable=True),
    sa.Column('units_res', sa.Integer(), nullable=True),
    sa.Column('units_total', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('built_far', sa.Float(), nullable=True),
    sa.Column('resid_far', sa.Float(), nullable=True),
    sa.Column('comm_far', sa.Float(), nullable=True),
    sa.Column('facil_far', sa.Float(), nullable=True),
    sa.Column('land_use', sa.String(length=2), nullable=True),
    sa.Column('zone_dist1', sa.String(length=20), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('assess_land', sa.BigInteger(), nullable=True),
    sa.Column('assess_tot', sa.BigInteger(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('pluto_version', sa.String(length=12), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('bbl')
    )
    with op.batch_alter_table('nyc_pluto_lot', schema=None) as batch_op:
        batch_op.create_index('ix_pluto_borough', ['borough'], unique=False)
        batch_op.create_index('ix_pluto_far', ['resid_far', 'built_far'], unique=False)
        batch_op.create_index('ix_pluto_landuse', ['land_use'], unique=False)
        batch_op.create_index('ix_pluto_zonedist1', ['zone_dist1'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nyc_pluto_lot', schema=None) as batch_op:
        batch_op.drop_index('ix_pluto_zonedist1')
        batch_op.drop_index('ix_pluto_landuse')
        batch_op.drop_index('ix_pluto_far')
        batch_op.drop_index('ix_pluto_borough')

    op.drop_table('nyc_pluto_lot')
    op.drop_table('bbl_cache')
    # ### end Alembic commands ###
